### ISSUE TITLE
use FullBlock replace CompactBlock for sync & executor

### ISSUE THREAD

**Issue by Pencil-Yao** [cita-cloud/rfcs#1]
executor get compact blcok also need to query transactions to execute, so directly give full block

controller get proposal but not have all transactions while need to sync transactions, so directly give proposal with full block

**Comment by rink1969** [comment]
直接给`executor`完整的区块信息，可以避免`executor`再去`storage`获取交易信息。这点对于错误处理来说是个很大的改善，这种跨多个微服务的调用，错误处理非常困难。

**Comment by rink1969** [comment]
广播`proposal`的时候直接用完整区块而不是`CompactBlock`，可以简化同步的逻辑，并且可以提高出块效率。现在遇到的一个问题就是同步进度与出块不匹配，经常把其他交易同步过来了，但是马上要出的块里面的交易还没同步过来，导致出块延迟。
