### ISSUE TITLE
gRPC错误处理

### ISSUE THREAD

**Issue by rink1969** [cita-cloud/rfcs#3]
参见 https://github.com/cita-cloud/controller_poc/issues/58

这个原则确定之后，需要对所有的微服务进行梳理，协议也可能要进行相应的调整。

**Comment by rink1969** [comment]
参考 https://liqiang.io/post/grpc-with-golang-part-04-client-retry-interceptor
最好还是用`gRPC`的错误码，这样可以用一些重试的库，里面可以自己列那些错误码需要重试。

**Comment by rink1969** [comment]
参考  https://grpc.github.io/grpc/core/md_doc_statuscodes.html
可以用于应用返回错误的有：
1. `InvalidArgument`
2. `NotFound`
3. `AlreadyExists`
4. `FailedPrecondition`
5. `Aborted`
6. `OutOfRange`
7. `DataLoss` 

如果是微服务在处理一个请求的过程中又调用了别的微服务产生了无法处理的错误，也要按照实际情况，设置合理的错误码给最开始的调用者。

**Comment by rink1969** [comment]
https://github.com/cita-cloud/rfcs/pull/7

**Comment by Pencil-Yao** [comment]
grpc的错误微服务层没有特殊的逻辑，这块更希望微服务的库提供判断能力，grpc的错误对应微服务层判断也是存在困难的，同时进入微服务层也不会报grpc错误，通过`status_code`微服务之间能知道发送的消息哪里存在错误
